environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: dns_lookup
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: false

test_script:
  - cargo test --target %TARGET%

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
