[package]
name = "dns-lookup"
version = "1.0.0"
authors = ["Josh Driver <keeperofdakeys@gmail.com>"]
description = "A simple dns resolving api, much like rust's unstable api. Also includes getaddrinfo and getnameinfo wrappers for libc variants."
documentation = "https://docs.rs/dns-lookup"
repository = "https://github.com/keeperofdakeys/dns-lookup/"
readme = "README.md"
keywords = ["dns", "resolve", "lookup", "getaddrinfo", "getnameinfo"]
license = "MIT/Apache-2.0"
include = [
    "src/**",
    "README.md",
    "LICENSE*",
    "Cargo.*"
]

[dependencies]
libc = "^0.2"
clippy = {version = "^0", optional = true}

[features]
default = []
